### ISSUE TITLE
检测脚本能支持Centos 7吗

### ISSUE THREAD

**Issue by QAQgithub2024** [lmc999/TikTokCheck#4]
![000](https://user-images.githubusercontent.com/91567869/176086275-f1246621-6924-478d-8710-7d80645c956d.jpg)
为啥不支持C7呀，，，

**Comment by lmc999** [comment]
centos7 curl版本太低，导致检测结果出现错误，因此不再支持centos7

**Comment by lionkingc** [comment]
CentOS Stream: syntax error in expression (error token is "Stream")

CentOS Stream 8 也不行吗
